# Generated by Django 3.0 on 2021-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210721_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imageproduct'),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
