# Generated by Django 3.0 on 2021-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210723_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='unit',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
